#!/usr/bin/env node
import { createHash } from "node:crypto";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const ROOT = resolve(import.meta.dirname, "..");
const DIST = join(ROOT, "dist");
const DEPLOY = join(ROOT, "deploy");
const CHECK = process.argv.includes("--check");

function* walk(dir) {
    for (const entry of readdirSync(dir, { withFileTypes: true })) {
        const path = join(dir, entry.name);
        if (path === DEPLOY) continue;
        if (entry.isDirectory()) yield* walk(path);
        else if (entry.name.endsWith(".html")) yield path;
    }
}

const INLINE = /<script(?![^>]*\bsrc=)([^>]*)>([\s\S]*?)<\/script>/g;
const EXECUTABLE = (attrs) => {
    const type = /\btype=["']([^"']+)["']/.exec(attrs)?.[1];
    return !type || type === "module" || /javascript|ecmascript/i.test(type);
};

const hashes = new Set();
for (const file of walk(DIST)) {
    for (const [, attrs, body] of readFileSync(file, "utf8").matchAll(INLINE)) {
        if (!EXECUTABLE(attrs)) continue;
        hashes.add(`'sha256-${createHash("sha256").update(body).digest("base64")}'`);
    }
}

const HEADERS = [
    `add_header Content-Security-Policy "${[
        "default-src 'none'",
        `script-src 'self' ${[...hashes].sort().join(" ")}`,
        "style-src 'self' 'unsafe-inline'",
        "img-src 'self' data:",
        "font-src 'self'",
        "connect-src 'self'",
        "manifest-src 'self'",
        "base-uri 'none'",
        "form-action 'none'",
        "frame-ancestors 'none'",
        "object-src 'none'",
        "upgrade-insecure-requests",
    ].join("; ")}" always;`,
    `add_header X-Content-Type-Options "nosniff" always;`,
    `add_header Referrer-Policy "no-referrer" always;`,
    `add_header Permissions-Policy "${[
        "accelerometer",
        "autoplay",
        "camera",
        "display-capture",
        "encrypted-media",
        "fullscreen",
        "geolocation",
        "gyroscope",
        "magnetometer",
        "microphone",
        "midi",
        "payment",
        "picture-in-picture",
        "usb",
        "xr-spatial-tracking",
    ].map((f) => `${f}=()`).join(", ")}" always;`,
    `add_header Cross-Origin-Opener-Policy "same-origin" always;`,
    `add_header Cross-Origin-Resource-Policy "same-origin" always;`,
    `add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;`,
].join("\n") + "\n";

const NGINX = `# lacort.ee — static site on the raspberry pi, fronted by cloudflared.
#
# Install:
#   sudo cp headers.conf /etc/nginx/snippets/lacort.ee-headers.conf
#   sudo cp nginx.conf    /etc/nginx/sites-available/lacort.ee
#   sudo ln -s /etc/nginx/sites-available/lacort.ee /etc/nginx/sites-enabled/
# cloudflared then points the tunnel at this port. Both files are
# regenerated by scripts/gen-headers.mjs on every build — the CSP carries
# the hash of the current inline scripts, so do not hand-edit it.

server {
    listen 80;
    listen [::]:80;
    server_name lacort.ee;

    root /var/www/lacort.ee;
    index index.html;
    error_page 404 /404.html;

    include /etc/nginx/snippets/lacort.ee-headers.conf;

    gzip on;
    gzip_comp_level 6;
    gzip_min_length 512;
    gzip_vary on;
    gzip_types text/plain text/css text/javascript application/javascript application/xml image/svg+xml;

    location /_astro/ {
        include /etc/nginx/snippets/lacort.ee-headers.conf;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    location /fonts/ {
        include /etc/nginx/snippets/lacort.ee-headers.conf;
        add_header Cache-Control "public, max-age=31536000, immutable";
        try_files $uri =404;
    }

    # 88x31 badges are hotlinked by other sites.
    location /buttons/ {
        include /etc/nginx/snippets/lacort.ee-headers.conf;
        add_header Cross-Origin-Resource-Policy cross-origin;
        add_header Access-Control-Allow-Origin *;
        add_header Cache-Control "public, max-age=604800";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
`;

if (CHECK) {
    for (const [name, content] of [
        ["deploy/headers.conf", HEADERS],
        ["deploy/nginx.conf", NGINX],
    ]) {
        let current = "";
        try {
            current = readFileSync(join(ROOT, name), "utf8");
        } catch {
            console.log(`${name} is missing. Run: node scripts/gen-headers.mjs`);
            process.exit(1);
        }
        if (current !== content) {
            console.log(
                `${name} is stale, an inline script changed and the CSP hash did not.\n` +
                    "Run: node scripts/gen-headers.mjs",
            );
            process.exit(1);
        }
    }
    console.log(`deploy/ matches the build (${hashes.size} inline script hash(es))`);
} else {
    writeFileSync(join(DEPLOY, "headers.conf"), HEADERS);
    writeFileSync(join(DEPLOY, "nginx.conf"), NGINX);
    console.log(
        `deploy/nginx.conf + deploy/headers.conf written, ${hashes.size} inline script hash(es) in the CSP`,
    );
    for (const h of hashes) console.log(`   ${h}`);
}
